import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "#05151b",
        surface: "#05151b",
        "surface-dim": "#05151b",
        "surface-bright": "#2c3b42",
        "surface-container-lowest": "#021016",
        "surface-container-low": "#0d1e24",
        "surface-container": "#122228",
        "surface-container-high": "#1c2c33",
        "surface-container-highest": "#27373e",
        "on-surface": "#d4e5ee",
        "on-surface-variant": "#bdc8d1",
        "inverse-surface": "#d4e5ee",
        "inverse-on-surface": "#233339",
        outline: "#87929b",
        "outline-variant": "#3e4850",
        "surface-tint": "#82cfff",
        primary: "#82cfff",
        "on-primary": "#00344b",
        "primary-container": "#00aeef",
        "on-primary-container": "#003e58",
        "inverse-primary": "#00658d",
        secondary: "#b4cad7",
        "on-secondary": "#1e333d",
        "secondary-container": "#374c57",
        "on-secondary-container": "#a6bcc8",
        tertiary: "#ffb876",
        "on-tertiary": "#4b2800",
        "tertiary-container": "#ea8c21",
        "on-tertiary-container": "#572f00",
        error: "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        "primary-fixed": "#c6e7ff",
        "primary-fixed-dim": "#82cfff",
        "on-primary-fixed": "#001e2d",
        "on-primary-fixed-variant": "#004c6b",
        "secondary-fixed": "#d0e6f3",
        "secondary-fixed-dim": "#b4cad7",
        "on-secondary-fixed": "#081e28",
        "on-secondary-fixed-variant": "#354a54",
        "tertiary-fixed": "#ffdcc0",
        "tertiary-fixed-dim": "#ffb876",
        "on-tertiary-fixed": "#2d1600",
        "on-tertiary-fixed-variant": "#6b3b00",
        "on-background": "#d4e5ee",
        "surface-variant": "#27373e",
      },
      fontFamily: {
        sans: ["Hanken Grotesk", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "display-lg": ["64px", { lineHeight: "72px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-lg-mobile": ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.1em", fontWeight: "500" }],
      },
      maxWidth: {
        "container-max": "1280px",
      },
      spacing: {
        "section-gap": "120px",
        "margin-desktop": "64px",
        "margin-mobile": "24px",
        gutter: "24px",
      },
      keyframes: {
        shimmer: {
          "0%": { backgroundPosition: "-200% 0" },
          "100%": { backgroundPosition: "200% 0" },
        },
        "slide-in-left": {
          "0%": { opacity: "0", transform: "translateX(-30px)" },
          "100%": { opacity: "1", transform: "translateX(0)" },
        },
        "fade-in": {
          "0%": { opacity: "0", transform: "translateY(20px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        twinkle: {
          "0%, 100%": { opacity: "0.2", transform: "scale(1)" },
          "50%": { opacity: "1", transform: "scale(1.5)" },
        },
        pulse: {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0.5" },
        },
      },
      animation: {
        shimmer: "shimmer 3s linear infinite",
        "slide-in-left": "slide-in-left 0.6s ease-out forwards",
        "fade-in": "fade-in 0.8s ease-out forwards",
        twinkle: "twinkle 3s ease-in-out infinite",
        pulse: "pulse 2s cubic-bezier(0.4,0,0.6,1) infinite",
      },
    },
  },
  plugins: [],
};

export default config;
